### ISSUE TITLE
Just an introduction!

### ISSUE THREAD

**Issue by daxaxelrod** [sujaysundar/FBLAQuiz#1]
Hi Sujay,

I’ll be judging your project for FBLA. I’ll be doing a deeper analysis in the coming weeks but just wanted to commend you on your thorough readme. I normally use Postgres so I might just change your db connection string. I recently upgraded to 3.8 so all good there. Did you make use of the new walrus operator := ? 

I’ll be using gh issues to provide feedback, or gh discussions if you enable it for this repo.

Best,
David

**Comment by sujaysundar** [comment]
Dear David Axelrod,

Thank you for your email! I really appreciate your feedback. I have enabled
github discussions now. Please let me know in case of any problems. Thank
you!

Sincerely, Sujay Sundar.
